### ISSUE TITLE
Commands not sent to DOMIQ Module

### ISSUE THREAD

**Issue by NickN-AH** [etobi/domiqtt#1]
Commands from MQTT bridge don't issue the meant command on the DOMIQ Module.
Maybe the format is wrong?

**Comment by etobi** [comment]
You have to provide more informations about what you are trying to archive and what command you are sending

**Comment by NickN-AH** [comment]
I have MQTT on IOBroker connected to domiqtt and domiqtt is connected to the DOMIQ module which acts as connector to my LCN system. 
I can see all the LCN values coming through via DOMIQ/domiqtt in the IOBroker MQTT. But when I want to publish
new values, I can see it in the domiqtt log but nothing happens on the DOMIQ module itself.

**Comment by NickN-AH** [comment]
13:44:13.708 INFO  < mqtt domiqtt/lcn/LCN/output/0/14/1/_brightness_state : 20
13:44:16.467 INFO  < mqtt domiqtt/lcn/LCN/output/0/14/1 : 20
13:44:37.102 INFO  < mqtt domiqtt/lcn/LCN/output/0/14/1/_state : OFF
13:44:41.694 INFO  < mqtt domiqtt/lcn/LCN/output/0/14/1/_state : ON

These are some entries that are generated in the log when I change values on IOBroker MQTT side.
Do I have to configure something special on DOMIQ module to receive and process these commands?

**Comment by etobi** [comment]
i dont think i did anything special on the DOMIQ module.

What happens, if you you use netcat / nc or telnet to connect to port 4224 on your Domiq?

`echo "LCN.output.0.14.1 = 100;ramp2" | nc 192.168.0.100 4224`

**Comment by etobi** [comment]
oh.. i just see: you are publishing the wrong mqtt topics.
_state messages are for reading the state - if you want to change something, you must use _set instead.

Read state changes:
`mosquitto_sub -h mqtt.localdomain -t domiqtt/lcn/LCN/output/0/14/1/_state`

change the state:
`mosquitto_pub -h mqtt.localdomain -t domiqtt/lcn/LCN/output/0/14/1/_set - m "ON"`

After changing the state using _set domiqtt will publish a _state message with the new state.

check https://github.com/etobi/domiqtt/blob/master/start.js#L136 for more special topic suffixes you could use.

**Comment by NickN-AH** [comment]
Great! This did the trick!
Thanks a lot!
